/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApprocheRouteImport } from './routes/approche'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as DemarrerRouteImport } from './routes/demarrer'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as RendezVousRouteImport } from './routes/rendez-vous'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SanteRouteImport } from './routes/sante'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EquipeIndexRouteImport } from './routes/equipe/index'
import { Route as EquipeIdRouteImport } from './routes/equipe/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprocheRoute = ApprocheRouteImport.update({
  id: '/approche',
  path: '/approche',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const DemarrerRoute = DemarrerRouteImport.update({
  id: '/demarrer',
  path: '/demarrer',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const RendezVousRoute = RendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SanteRoute = SanteRouteImport.update({
  id: '/sante',
  path: '/sante',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeIndexRoute = EquipeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipeRoute,
} as any)
const EquipeIdRoute = EquipeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EquipeRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/approche': typeof ApprocheRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/demarrer': typeof DemarrerRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/rendez-vous': typeof RendezVousRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sante': typeof SanteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/equipe/$id': typeof EquipeIdRoute
  '/equipe/': typeof EquipeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/approche': typeof ApprocheRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/demarrer': typeof DemarrerRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/rendez-vous': typeof RendezVousRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sante': typeof SanteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/equipe/$id': typeof EquipeIdRoute
  '/equipe': typeof EquipeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/approche': typeof ApprocheRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/demarrer': typeof DemarrerRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/rendez-vous': typeof RendezVousRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sante': typeof SanteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/equipe/$id': typeof EquipeIdRoute
  '/equipe/': typeof EquipeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/approche'
    | '/conditions'
    | '/confidentialite'
    | '/demarrer'
    | '/equipe'
    | '/login'
    | '/mentions-legales'
    | '/rendez-vous'
    | '/robots.txt'
    | '/sante'
    | '/services'
    | '/sitemap.xml'
    | '/equipe/$id'
    | '/equipe/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/approche'
    | '/conditions'
    | '/confidentialite'
    | '/demarrer'
    | '/login'
    | '/mentions-legales'
    | '/rendez-vous'
    | '/robots.txt'
    | '/sante'
    | '/services'
    | '/sitemap.xml'
    | '/equipe/$id'
    | '/equipe'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/approche'
    | '/conditions'
    | '/confidentialite'
    | '/demarrer'
    | '/equipe'
    | '/login'
    | '/mentions-legales'
    | '/rendez-vous'
    | '/robots.txt'
    | '/sante'
    | '/services'
    | '/sitemap.xml'
    | '/equipe/$id'
    | '/equipe/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApprocheRoute: typeof ApprocheRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  DemarrerRoute: typeof DemarrerRoute
  EquipeRoute: typeof EquipeRouteWithChildren
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  RendezVousRoute: typeof RendezVousRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SanteRoute: typeof SanteRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approche': {
      id: '/approche'
      path: '/approche'
      fullPath: '/approche'
      preLoaderRoute: typeof ApprocheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demarrer': {
      id: '/demarrer'
      path: '/demarrer'
      fullPath: '/demarrer'
      preLoaderRoute: typeof DemarrerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendez-vous': {
      id: '/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof RendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sante': {
      id: '/sante'
      path: '/sante'
      fullPath: '/sante'
      preLoaderRoute: typeof SanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/': {
      id: '/equipe/'
      path: '/'
      fullPath: '/equipe/'
      preLoaderRoute: typeof EquipeIndexRouteImport
      parentRoute: typeof EquipeRoute
    }
    '/equipe/$id': {
      id: '/equipe/$id'
      path: '/$id'
      fullPath: '/equipe/$id'
      preLoaderRoute: typeof EquipeIdRouteImport
      parentRoute: typeof EquipeRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EquipeRouteChildren {
  EquipeIdRoute: typeof EquipeIdRoute
  EquipeIndexRoute: typeof EquipeIndexRoute
}

const EquipeRouteChildren: EquipeRouteChildren = {
  EquipeIdRoute: EquipeIdRoute,
  EquipeIndexRoute: EquipeIndexRoute,
}

const EquipeRouteWithChildren =
  EquipeRoute._addFileChildren(EquipeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApprocheRoute: ApprocheRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  DemarrerRoute: DemarrerRoute,
  EquipeRoute: EquipeRouteWithChildren,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  RendezVousRoute: RendezVousRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SanteRoute: SanteRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
